Add database
vladbakushkin/java-filmorate pull request #11
Opened 2024-03-24 20:31 UTC by vladbakushkin

Добавлено сохранение состояния данных в БД.

2024-03-25 09:13 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-03-25 09:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +    NAME CHARACTER VARYING,
1. В таких полях стоит ограничивать длину
2. Это поле должно иметь ограничение `not null`

2024-03-25 09:13 UTC, LexLippi commented on src/main/resources/clean.sql
> +DROP TABLE FILM_GENRE;
От этой миграции стоит избавиться, так как ни один пользователь не захочет пользоваться сервисом, где его данные будут удаляться при обновлении

2024-03-25 09:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +    DURATION     INTEGER,
Тут наверное `not null`

2024-03-25 09:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +    NAME         CHARACTER VARYING not null,
Необходимо ограничение на длину

2024-03-25 09:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +    NAME CHARACTER VARYING,
Замечания аналогичные тем, что указано выше

2024-03-25 09:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +    NAME     CHARACTER VARYING,
ограничение на длину

2024-03-25 09:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +    FRIEND_STATUS_CONFIRM BOOLEAN,
`not null`

2024-03-25 16:46 UTC, vladbakushkin commented on src/main/resources/schema.sql
> +    NAME CHARACTER VARYING,
Сделано

2024-03-25 16:48 UTC, vladbakushkin commented on src/main/resources/schema.sql
> +    DURATION     INTEGER,
Сделано

2024-03-25 16:49 UTC, vladbakushkin commented on src/main/resources/schema.sql
> +    NAME         CHARACTER VARYING not null,
Сделано

2024-03-25 16:50 UTC, vladbakushkin commented on src/main/resources/schema.sql
> +    NAME CHARACTER VARYING,
Сделано

2024-03-25 16:50 UTC, vladbakushkin commented on src/main/resources/schema.sql
> +    NAME     CHARACTER VARYING,
Сделано

2024-03-25 16:52 UTC, vladbakushkin commented on src/main/resources/schema.sql
> +    FRIEND_STATUS_CONFIRM BOOLEAN,
Сделано

2024-03-25 17:05 UTC, vladbakushkin commented on src/main/resources/clean.sql
> +DROP TABLE FILM_GENRE;
Этот скрипт был написал для быстрой очистки БД. Я решил его удалить совсем.
Сделано

2024-03-26 07:11 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-03-28 16:40 UTC, merged