add solution
vladbakushkin/java-filmorate pull request #5
Opened 2024-02-05 19:44 UTC by vladbakushkin

2024-02-06 06:22 UTC, LexLippi requested changes
Привет!

Отличаня работа!

Есть пара мелких замечаний, которые необходимо исправить!

Желаю удачи!

2024-02-06 06:22 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/utils/GeneratorId.java
> +public class GeneratorId {
Странное решение с этим классом. 
Если ты вынес логику в отдельный класс, то имеет смысл завести одно не статическое поле `id` и метод `generateNewId()`. 
Тогда просто можно будет в разные контроллеры передать два объекта класса `GeneratorId` и работать с ним везде абсолютно одинаково

2024-02-06 06:22 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Такого фильма нет в базе.");
Лучше в хранилище, а не в базе, потому что никакой базы у нас нет, и она не должна обязательно присутствовать, а хранилище может быть любым. Например `in-memory` как у нас

2024-02-06 18:03 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/utils/GeneratorId.java
> +public class GeneratorId {
Хотел вынести хранилище идентификаторов в отдельный класс, но видимо перемудрил немного

2024-02-07 08:41 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-02-07 17:48 UTC, merged