Add friends likes
vladbakushkin/java-filmorate pull request #6
Opened 2024-02-18 21:26 UTC by vladbakushkin

2024-02-19 09:51 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необхожимо исправить!

Желаю удачи!

2024-02-19 09:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/ErrorResponse.java
> +    String message;
модификаторы доступа

2024-02-19 09:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;    // id пользователей лайкнувших фильм
Переопределить метод `getLikes`, чтобы он возвращал копию коллекции лайков, иначе это нарущает инкапсуляцию и добавить методы: `addLike`, `removeLike`

2024-02-19 09:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
Аналогичное замечание, как и в классе `Film`

2024-02-19 09:51 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Comparator<Film> likesComparatorDesc = likesComparatorAsc.reversed();
Компаратор не меняется от вызова к вызову, стоит сделать его константой класса

2024-02-19 18:23 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/ErrorResponse.java
> +    String message;
исправил

2024-02-19 18:23 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;    // id пользователей лайкнувших фильм
исправил

2024-02-20 07:44 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-02-20 17:33 UTC, merged